/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AuthenticatedWhatsNewRouteImport } from './routes/_authenticated/whats-new'
import { Route as AuthenticatedVirtuesRouteImport } from './routes/_authenticated/virtues'
import { Route as AuthenticatedTrelloCallbackRouteImport } from './routes/_authenticated/trello-callback'
import { Route as AuthenticatedSupportRouteImport } from './routes/_authenticated/support'
import { Route as AuthenticatedStoreRouteImport } from './routes/_authenticated/store'
import { Route as AuthenticatedSkillTreeRouteImport } from './routes/_authenticated/skill-tree'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedRemindersRouteImport } from './routes/_authenticated/reminders'
import { Route as AuthenticatedProgressRouteImport } from './routes/_authenticated/progress'
import { Route as AuthenticatedPriorityMatrixRouteImport } from './routes/_authenticated/priority-matrix'
import { Route as AuthenticatedMissionsRouteImport } from './routes/_authenticated/missions'
import { Route as AuthenticatedMinigameRouteImport } from './routes/_authenticated/minigame'
import { Route as AuthenticatedHowItWorksRouteImport } from './routes/_authenticated/how-it-works'
import { Route as AuthenticatedHabitsRouteImport } from './routes/_authenticated/habits'
import { Route as AuthenticatedFinanceRouteImport } from './routes/_authenticated/finance'
import { Route as AuthenticatedFailureZoneRouteImport } from './routes/_authenticated/failure-zone'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCollectionRouteImport } from './routes/_authenticated/collection'
import { Route as AuthenticatedCalendarRouteImport } from './routes/_authenticated/calendar'
import { Route as AuthenticatedAvatarsRouteImport } from './routes/_authenticated/avatars'
import { Route as AuthenticatedAttributesRouteImport } from './routes/_authenticated/attributes'
import { Route as AuthenticatedArenaRouteImport } from './routes/_authenticated/arena'
import { Route as AuthenticatedArchitectRouteImport } from './routes/_authenticated/architect'
import { Route as AuthenticatedAiChatRouteImport } from './routes/_authenticated/ai-chat'
import { Route as AuthenticatedAchievementsRouteImport } from './routes/_authenticated/achievements'
import { Route as AuthenticatedBoardsIndexRouteImport } from './routes/_authenticated/boards.index'
import { Route as AuthenticatedBoardsBoardIdRouteImport } from './routes/_authenticated/boards.$boardId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWhatsNewRoute = AuthenticatedWhatsNewRouteImport.update({
  id: '/whats-new',
  path: '/whats-new',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedVirtuesRoute = AuthenticatedVirtuesRouteImport.update({
  id: '/virtues',
  path: '/virtues',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTrelloCallbackRoute =
  AuthenticatedTrelloCallbackRouteImport.update({
    id: '/trello-callback',
    path: '/trello-callback',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSupportRoute = AuthenticatedSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedStoreRoute = AuthenticatedStoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSkillTreeRoute = AuthenticatedSkillTreeRouteImport.update({
  id: '/skill-tree',
  path: '/skill-tree',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRemindersRoute = AuthenticatedRemindersRouteImport.update({
  id: '/reminders',
  path: '/reminders',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProgressRoute = AuthenticatedProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPriorityMatrixRoute =
  AuthenticatedPriorityMatrixRouteImport.update({
    id: '/priority-matrix',
    path: '/priority-matrix',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMissionsRoute = AuthenticatedMissionsRouteImport.update({
  id: '/missions',
  path: '/missions',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMinigameRoute = AuthenticatedMinigameRouteImport.update({
  id: '/minigame',
  path: '/minigame',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHowItWorksRoute = AuthenticatedHowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHabitsRoute = AuthenticatedHabitsRouteImport.update({
  id: '/habits',
  path: '/habits',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFinanceRoute = AuthenticatedFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFailureZoneRoute =
  AuthenticatedFailureZoneRouteImport.update({
    id: '/failure-zone',
    path: '/failure-zone',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCollectionRoute = AuthenticatedCollectionRouteImport.update({
  id: '/collection',
  path: '/collection',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCalendarRoute = AuthenticatedCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAvatarsRoute = AuthenticatedAvatarsRouteImport.update({
  id: '/avatars',
  path: '/avatars',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAttributesRoute = AuthenticatedAttributesRouteImport.update({
  id: '/attributes',
  path: '/attributes',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedArenaRoute = AuthenticatedArenaRouteImport.update({
  id: '/arena',
  path: '/arena',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedArchitectRoute = AuthenticatedArchitectRouteImport.update({
  id: '/architect',
  path: '/architect',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAiChatRoute = AuthenticatedAiChatRouteImport.update({
  id: '/ai-chat',
  path: '/ai-chat',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAchievementsRoute =
  AuthenticatedAchievementsRouteImport.update({
    id: '/achievements',
    path: '/achievements',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedBoardsIndexRoute =
  AuthenticatedBoardsIndexRouteImport.update({
    id: '/boards/',
    path: '/boards/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedBoardsBoardIdRoute =
  AuthenticatedBoardsBoardIdRouteImport.update({
    id: '/boards/$boardId',
    path: '/boards/$boardId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/achievements': typeof AuthenticatedAchievementsRoute
  '/ai-chat': typeof AuthenticatedAiChatRoute
  '/architect': typeof AuthenticatedArchitectRoute
  '/arena': typeof AuthenticatedArenaRoute
  '/attributes': typeof AuthenticatedAttributesRoute
  '/avatars': typeof AuthenticatedAvatarsRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/collection': typeof AuthenticatedCollectionRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/failure-zone': typeof AuthenticatedFailureZoneRoute
  '/finance': typeof AuthenticatedFinanceRoute
  '/habits': typeof AuthenticatedHabitsRoute
  '/how-it-works': typeof AuthenticatedHowItWorksRoute
  '/minigame': typeof AuthenticatedMinigameRoute
  '/missions': typeof AuthenticatedMissionsRoute
  '/priority-matrix': typeof AuthenticatedPriorityMatrixRoute
  '/progress': typeof AuthenticatedProgressRoute
  '/reminders': typeof AuthenticatedRemindersRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/skill-tree': typeof AuthenticatedSkillTreeRoute
  '/store': typeof AuthenticatedStoreRoute
  '/support': typeof AuthenticatedSupportRoute
  '/trello-callback': typeof AuthenticatedTrelloCallbackRoute
  '/virtues': typeof AuthenticatedVirtuesRoute
  '/whats-new': typeof AuthenticatedWhatsNewRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/boards/$boardId': typeof AuthenticatedBoardsBoardIdRoute
  '/boards/': typeof AuthenticatedBoardsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/achievements': typeof AuthenticatedAchievementsRoute
  '/ai-chat': typeof AuthenticatedAiChatRoute
  '/architect': typeof AuthenticatedArchitectRoute
  '/arena': typeof AuthenticatedArenaRoute
  '/attributes': typeof AuthenticatedAttributesRoute
  '/avatars': typeof AuthenticatedAvatarsRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/collection': typeof AuthenticatedCollectionRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/failure-zone': typeof AuthenticatedFailureZoneRoute
  '/finance': typeof AuthenticatedFinanceRoute
  '/habits': typeof AuthenticatedHabitsRoute
  '/how-it-works': typeof AuthenticatedHowItWorksRoute
  '/minigame': typeof AuthenticatedMinigameRoute
  '/missions': typeof AuthenticatedMissionsRoute
  '/priority-matrix': typeof AuthenticatedPriorityMatrixRoute
  '/progress': typeof AuthenticatedProgressRoute
  '/reminders': typeof AuthenticatedRemindersRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/skill-tree': typeof AuthenticatedSkillTreeRoute
  '/store': typeof AuthenticatedStoreRoute
  '/support': typeof AuthenticatedSupportRoute
  '/trello-callback': typeof AuthenticatedTrelloCallbackRoute
  '/virtues': typeof AuthenticatedVirtuesRoute
  '/whats-new': typeof AuthenticatedWhatsNewRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/boards/$boardId': typeof AuthenticatedBoardsBoardIdRoute
  '/boards': typeof AuthenticatedBoardsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/achievements': typeof AuthenticatedAchievementsRoute
  '/_authenticated/ai-chat': typeof AuthenticatedAiChatRoute
  '/_authenticated/architect': typeof AuthenticatedArchitectRoute
  '/_authenticated/arena': typeof AuthenticatedArenaRoute
  '/_authenticated/attributes': typeof AuthenticatedAttributesRoute
  '/_authenticated/avatars': typeof AuthenticatedAvatarsRoute
  '/_authenticated/calendar': typeof AuthenticatedCalendarRoute
  '/_authenticated/collection': typeof AuthenticatedCollectionRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/failure-zone': typeof AuthenticatedFailureZoneRoute
  '/_authenticated/finance': typeof AuthenticatedFinanceRoute
  '/_authenticated/habits': typeof AuthenticatedHabitsRoute
  '/_authenticated/how-it-works': typeof AuthenticatedHowItWorksRoute
  '/_authenticated/minigame': typeof AuthenticatedMinigameRoute
  '/_authenticated/missions': typeof AuthenticatedMissionsRoute
  '/_authenticated/priority-matrix': typeof AuthenticatedPriorityMatrixRoute
  '/_authenticated/progress': typeof AuthenticatedProgressRoute
  '/_authenticated/reminders': typeof AuthenticatedRemindersRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/skill-tree': typeof AuthenticatedSkillTreeRoute
  '/_authenticated/store': typeof AuthenticatedStoreRoute
  '/_authenticated/support': typeof AuthenticatedSupportRoute
  '/_authenticated/trello-callback': typeof AuthenticatedTrelloCallbackRoute
  '/_authenticated/virtues': typeof AuthenticatedVirtuesRoute
  '/_authenticated/whats-new': typeof AuthenticatedWhatsNewRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/_authenticated/boards/$boardId': typeof AuthenticatedBoardsBoardIdRoute
  '/_authenticated/boards/': typeof AuthenticatedBoardsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/achievements'
    | '/ai-chat'
    | '/architect'
    | '/arena'
    | '/attributes'
    | '/avatars'
    | '/calendar'
    | '/collection'
    | '/dashboard'
    | '/failure-zone'
    | '/finance'
    | '/habits'
    | '/how-it-works'
    | '/minigame'
    | '/missions'
    | '/priority-matrix'
    | '/progress'
    | '/reminders'
    | '/settings'
    | '/skill-tree'
    | '/store'
    | '/support'
    | '/trello-callback'
    | '/virtues'
    | '/whats-new'
    | '/auth/callback'
    | '/boards/$boardId'
    | '/boards/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/achievements'
    | '/ai-chat'
    | '/architect'
    | '/arena'
    | '/attributes'
    | '/avatars'
    | '/calendar'
    | '/collection'
    | '/dashboard'
    | '/failure-zone'
    | '/finance'
    | '/habits'
    | '/how-it-works'
    | '/minigame'
    | '/missions'
    | '/priority-matrix'
    | '/progress'
    | '/reminders'
    | '/settings'
    | '/skill-tree'
    | '/store'
    | '/support'
    | '/trello-callback'
    | '/virtues'
    | '/whats-new'
    | '/auth/callback'
    | '/boards/$boardId'
    | '/boards'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/achievements'
    | '/_authenticated/ai-chat'
    | '/_authenticated/architect'
    | '/_authenticated/arena'
    | '/_authenticated/attributes'
    | '/_authenticated/avatars'
    | '/_authenticated/calendar'
    | '/_authenticated/collection'
    | '/_authenticated/dashboard'
    | '/_authenticated/failure-zone'
    | '/_authenticated/finance'
    | '/_authenticated/habits'
    | '/_authenticated/how-it-works'
    | '/_authenticated/minigame'
    | '/_authenticated/missions'
    | '/_authenticated/priority-matrix'
    | '/_authenticated/progress'
    | '/_authenticated/reminders'
    | '/_authenticated/settings'
    | '/_authenticated/skill-tree'
    | '/_authenticated/store'
    | '/_authenticated/support'
    | '/_authenticated/trello-callback'
    | '/_authenticated/virtues'
    | '/_authenticated/whats-new'
    | '/auth/callback'
    | '/_authenticated/boards/$boardId'
    | '/_authenticated/boards/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/whats-new': {
      id: '/_authenticated/whats-new'
      path: '/whats-new'
      fullPath: '/whats-new'
      preLoaderRoute: typeof AuthenticatedWhatsNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/virtues': {
      id: '/_authenticated/virtues'
      path: '/virtues'
      fullPath: '/virtues'
      preLoaderRoute: typeof AuthenticatedVirtuesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/trello-callback': {
      id: '/_authenticated/trello-callback'
      path: '/trello-callback'
      fullPath: '/trello-callback'
      preLoaderRoute: typeof AuthenticatedTrelloCallbackRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/support': {
      id: '/_authenticated/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof AuthenticatedSupportRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/store': {
      id: '/_authenticated/store'
      path: '/store'
      fullPath: '/store'
      preLoaderRoute: typeof AuthenticatedStoreRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/skill-tree': {
      id: '/_authenticated/skill-tree'
      path: '/skill-tree'
      fullPath: '/skill-tree'
      preLoaderRoute: typeof AuthenticatedSkillTreeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reminders': {
      id: '/_authenticated/reminders'
      path: '/reminders'
      fullPath: '/reminders'
      preLoaderRoute: typeof AuthenticatedRemindersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/progress': {
      id: '/_authenticated/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof AuthenticatedProgressRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/priority-matrix': {
      id: '/_authenticated/priority-matrix'
      path: '/priority-matrix'
      fullPath: '/priority-matrix'
      preLoaderRoute: typeof AuthenticatedPriorityMatrixRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/missions': {
      id: '/_authenticated/missions'
      path: '/missions'
      fullPath: '/missions'
      preLoaderRoute: typeof AuthenticatedMissionsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/minigame': {
      id: '/_authenticated/minigame'
      path: '/minigame'
      fullPath: '/minigame'
      preLoaderRoute: typeof AuthenticatedMinigameRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/how-it-works': {
      id: '/_authenticated/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof AuthenticatedHowItWorksRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/habits': {
      id: '/_authenticated/habits'
      path: '/habits'
      fullPath: '/habits'
      preLoaderRoute: typeof AuthenticatedHabitsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/finance': {
      id: '/_authenticated/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof AuthenticatedFinanceRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/failure-zone': {
      id: '/_authenticated/failure-zone'
      path: '/failure-zone'
      fullPath: '/failure-zone'
      preLoaderRoute: typeof AuthenticatedFailureZoneRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/collection': {
      id: '/_authenticated/collection'
      path: '/collection'
      fullPath: '/collection'
      preLoaderRoute: typeof AuthenticatedCollectionRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/calendar': {
      id: '/_authenticated/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AuthenticatedCalendarRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/avatars': {
      id: '/_authenticated/avatars'
      path: '/avatars'
      fullPath: '/avatars'
      preLoaderRoute: typeof AuthenticatedAvatarsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/attributes': {
      id: '/_authenticated/attributes'
      path: '/attributes'
      fullPath: '/attributes'
      preLoaderRoute: typeof AuthenticatedAttributesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/arena': {
      id: '/_authenticated/arena'
      path: '/arena'
      fullPath: '/arena'
      preLoaderRoute: typeof AuthenticatedArenaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/architect': {
      id: '/_authenticated/architect'
      path: '/architect'
      fullPath: '/architect'
      preLoaderRoute: typeof AuthenticatedArchitectRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ai-chat': {
      id: '/_authenticated/ai-chat'
      path: '/ai-chat'
      fullPath: '/ai-chat'
      preLoaderRoute: typeof AuthenticatedAiChatRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/achievements': {
      id: '/_authenticated/achievements'
      path: '/achievements'
      fullPath: '/achievements'
      preLoaderRoute: typeof AuthenticatedAchievementsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/boards/': {
      id: '/_authenticated/boards/'
      path: '/boards'
      fullPath: '/boards/'
      preLoaderRoute: typeof AuthenticatedBoardsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/boards/$boardId': {
      id: '/_authenticated/boards/$boardId'
      path: '/boards/$boardId'
      fullPath: '/boards/$boardId'
      preLoaderRoute: typeof AuthenticatedBoardsBoardIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAchievementsRoute: typeof AuthenticatedAchievementsRoute
  AuthenticatedAiChatRoute: typeof AuthenticatedAiChatRoute
  AuthenticatedArchitectRoute: typeof AuthenticatedArchitectRoute
  AuthenticatedArenaRoute: typeof AuthenticatedArenaRoute
  AuthenticatedAttributesRoute: typeof AuthenticatedAttributesRoute
  AuthenticatedAvatarsRoute: typeof AuthenticatedAvatarsRoute
  AuthenticatedCalendarRoute: typeof AuthenticatedCalendarRoute
  AuthenticatedCollectionRoute: typeof AuthenticatedCollectionRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedFailureZoneRoute: typeof AuthenticatedFailureZoneRoute
  AuthenticatedFinanceRoute: typeof AuthenticatedFinanceRoute
  AuthenticatedHabitsRoute: typeof AuthenticatedHabitsRoute
  AuthenticatedHowItWorksRoute: typeof AuthenticatedHowItWorksRoute
  AuthenticatedMinigameRoute: typeof AuthenticatedMinigameRoute
  AuthenticatedMissionsRoute: typeof AuthenticatedMissionsRoute
  AuthenticatedPriorityMatrixRoute: typeof AuthenticatedPriorityMatrixRoute
  AuthenticatedProgressRoute: typeof AuthenticatedProgressRoute
  AuthenticatedRemindersRoute: typeof AuthenticatedRemindersRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedSkillTreeRoute: typeof AuthenticatedSkillTreeRoute
  AuthenticatedStoreRoute: typeof AuthenticatedStoreRoute
  AuthenticatedSupportRoute: typeof AuthenticatedSupportRoute
  AuthenticatedTrelloCallbackRoute: typeof AuthenticatedTrelloCallbackRoute
  AuthenticatedVirtuesRoute: typeof AuthenticatedVirtuesRoute
  AuthenticatedWhatsNewRoute: typeof AuthenticatedWhatsNewRoute
  AuthenticatedBoardsBoardIdRoute: typeof AuthenticatedBoardsBoardIdRoute
  AuthenticatedBoardsIndexRoute: typeof AuthenticatedBoardsIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAchievementsRoute: AuthenticatedAchievementsRoute,
  AuthenticatedAiChatRoute: AuthenticatedAiChatRoute,
  AuthenticatedArchitectRoute: AuthenticatedArchitectRoute,
  AuthenticatedArenaRoute: AuthenticatedArenaRoute,
  AuthenticatedAttributesRoute: AuthenticatedAttributesRoute,
  AuthenticatedAvatarsRoute: AuthenticatedAvatarsRoute,
  AuthenticatedCalendarRoute: AuthenticatedCalendarRoute,
  AuthenticatedCollectionRoute: AuthenticatedCollectionRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedFailureZoneRoute: AuthenticatedFailureZoneRoute,
  AuthenticatedFinanceRoute: AuthenticatedFinanceRoute,
  AuthenticatedHabitsRoute: AuthenticatedHabitsRoute,
  AuthenticatedHowItWorksRoute: AuthenticatedHowItWorksRoute,
  AuthenticatedMinigameRoute: AuthenticatedMinigameRoute,
  AuthenticatedMissionsRoute: AuthenticatedMissionsRoute,
  AuthenticatedPriorityMatrixRoute: AuthenticatedPriorityMatrixRoute,
  AuthenticatedProgressRoute: AuthenticatedProgressRoute,
  AuthenticatedRemindersRoute: AuthenticatedRemindersRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedSkillTreeRoute: AuthenticatedSkillTreeRoute,
  AuthenticatedStoreRoute: AuthenticatedStoreRoute,
  AuthenticatedSupportRoute: AuthenticatedSupportRoute,
  AuthenticatedTrelloCallbackRoute: AuthenticatedTrelloCallbackRoute,
  AuthenticatedVirtuesRoute: AuthenticatedVirtuesRoute,
  AuthenticatedWhatsNewRoute: AuthenticatedWhatsNewRoute,
  AuthenticatedBoardsBoardIdRoute: AuthenticatedBoardsBoardIdRoute,
  AuthenticatedBoardsIndexRoute: AuthenticatedBoardsIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  AuthCallbackRoute: AuthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
